[workspace]
members = [
    "./",
    "crates/fsdoctor-core",
]
resolver = "2"

[workspace.package]
version                 = "0.1.0"
description             = "A cross-platform backup/file-share integrity checker"
authors                 = ["mrbya <v.toth.svk2@gmail.com>"]
edition                 = "2021"
license                 = "MIT"

[package]
name                    = "fsdoctor"
version.workspace       = true
description.workspace   = true
authors.workspace       = true
edition.workspace       = true
license.workspace       = true

[workspace.dependencies]
# Build
tauri-build             = { version = "2", features = [] }
# Internal crates
fsdoctor-core           = { path = "crates/fsdoctor-core" }
# Runtime
tauri                   = { version = "2", features = [] }
tauri-plugin-opener     = { version = "2" }
serde                   = { version = "1", features = ["derive"] }
serde_json              = { version = "1" }
thiserror               = { version = "2" }
sqlx                    = { version = "0.9", features = ["sqlite", "time", "macros", "migrate", "runtime-tokio"] }
time                    = { version = "0.3" }
tokio                   = { version = "1", features = ["macros", "rt-multi-thread", "sync"] }
blake3                  = { version = "1" }
# Dev
criterion               = { version = "0.8" }
pretty_assertions       = { version = "1" }
tempfile                = { version = "3" }

[lib]
name = "fsdoctor_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build.workspace = true

[dependencies]
tauri.workspace = true
tauri-plugin-opener.workspace = true
serde.workspace = true
serde_json.workspace = true
fsdoctor-core.workspace = true

[package.metadata.cargo-udeps.ignore]
normal = [
    "fsdoctor-core"
]
development = ["criterion", "pretty_assertions"]
